### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by zyh4482** [idptools/finches#3]
Thanks for your great work! 

I'm trying to deploy `finches` locally with following command:

```
conda create -n albatross
conda activate albatross

pip install git+https://git@github.com/idptools/sparrow.git
pip install idptools-parrot[optimize]
pip install afrc

conda install numpy pytorch scipy cython matplotlib jupyter -c pytorch -n albatross
conda install mdtraj -n albatross
pip install git+https://git@github.com/idptools/finches.git
```
Because I'm also working on something else using other tools developed by your group, I installed `finches` in the same environment. Before `pip install` finches, everything went well. Then it returns error message as below: 

```
Collecting git+https://****@github.com/idptools/finches.git                     
  Cloning https://****@github.com/idptools/finches.git to /tmp/pip-req-build-wqefo1ty                                                                           
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/idptools/finches.git' /tmp/pip-req-build-wqefo1ty                               
  Resolved https://****@github.com/idptools/finches.git to commit 7e1973b74d34208efa6bba4830f2550c11bd71a9                                                      
  Installing build dependencies ... done                                        
  Getting requirements to build wheel ... done                                  
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./software/miniforge3/envs/albatross/lib/python3.12/site-packages (from finches==0.1.1+9.g7e1973b) (1.26.4)
Collecting afrc>=0.3.4 (from finches==0.1.1+9.g7e1973b)
  Using cached afrc-0.3.4.tar.gz (58 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-9yx7l3mw/afrc_27a44d5c2f3f4a058a84111dcfcb43f9/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9yx7l3mw/afrc_27a44d5c2f3f4a058a84111dcfcb43f9/setup.py", line 30, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-9yx7l3mw/afrc_27a44d5c2f3f4a058a84111dcfcb43f9/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-9yx7l3mw/afrc_27a44d5c2f3f4a058a84111dcfcb43f9/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-9yx7l3mw/afrc_27a44d5c2f3f4a058a84111dcfcb43f9/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It seems that there is some mistaken usage of attribute from `configparser`. I tried to install `configparser` and `versioneer 0.29` . It does not work. 

A similar issue is [found here](https://github.com/pydata/pandas-datareader/issues/969).

Would you mind checking this issue? Thank you very much!

**Comment by zyh4482** [comment]
I've confirmed it is issue related to miscompatible version of python. 

The installation works only for `python <= 3.11`. In `python >=3.12`, [configparser](https://docs.python.org/3/library/configparser.html#module-configparser) no longer has a `SafeConfigParser` class, which caused the error: `AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`

I'm closing this issue.
